### ISSUE TITLE
Error when running as external library inside IDEA

### ISSUE THREAD

**Issue by LFra** [shiffman/OpenKinect-for-Processing#105]
Hi,
since I'm really comfortable with the IntelliJ software, I would love to use this plugin inside IDEA. I keep getting this error inside Main.java: 

`java.lang.NoClassDefFoundError: com/jogamp/opengl/GLException
	at processing.opengl.PGraphicsOpenGL.createPGL(PGraphicsOpenGL.java:668)
	at processing.opengl.PGraphicsOpenGL.<init>(PGraphicsOpenGL.java:532)
	at processing.opengl.PGraphics2D.<init>(PGraphics2D.java:36)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at processing.core.PApplet.makeGraphics(PApplet.java:2227)
	at processing.core.PApplet.createPrimaryGraphics(PApplet.java:2306)
	at processing.core.PApplet.initSurface(PApplet.java:10553)
	at processing.core.PApplet.runSketch(PApplet.java:10492)
	at processing.core.PApplet.main(PApplet.java:10211)
	at Main.main(Main.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)`

_Main.java_
`import processing.core.PApplet;

public class Main {
    private final static String[] OPTIONS = new String[] { "Sketch" };

    public static void main(String[] args) {
        PApplet.main(OPTIONS);
    }
}`

_Sketch.java_
`import processing.core.*;
import org.openkinect.processing.*;

public class Sketch extends PApplet {
    private Kinect2 kinect2;

    public void settings() {
        size(512, 424, P2D);
    }

    public void setup(){
        kinect2 = new Kinect2(this);

        kinect2.initDepth();
        kinect2.initDevice();
    }

    public void draw() {
        background(0);

        PImage depth = kinect2.getDepthImage();
        image(depth, 0, 0);
    }

}
`

How to fix this?

**Comment by LFra** [comment]
Ok solved, missed some of the OpenGL libs.
