### ISSUE TITLE
Eclipse new Kinect(this) falied

### ISSUE THREAD

**Issue by DQvsRA** [shiffman/OpenKinect-for-Processing#51]
Hello.
I use Eclipse as my main IDE for Processing with Proclipsing plugin.
My setting is:
1. Processing 3.0.1
2. OS: Ubuntu

This is my code:

package noiseink;

import processing.core.PApplet;

import org.openkinect.processing.*;

public class NoiseInk extends PApplet {
	// Kinect Library object
	Kinect kinect;

	// Angle for rotation
	float a = 0;

	// We'll use a lookup table so that we don't have to repeat the math over and over
	float[] depthLookUp = new float[2048];
	
	public void settings() {
		size(500, 500);
		kinect = new Kinect(this);
		kinect.initDepth();
	}
	
	public void draw() {
		background(0);
	}
	
	public static void main(String _args[]) {
		PApplet.main(new String[] { noiseink.NoiseInk.class.getName() });
	}
}

And it's crashed with this error

Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jna/Library
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.openkinect.processing.Kinect.<init>(Unknown Source)
	at noiseink.NoiseInk.settings(NoiseInk.java:19)
	at processing.core.PApplet.handleSettings(PApplet.java:962)
	at processing.core.PApplet.runSketch(PApplet.java:10234)
	at processing.core.PApplet.main(PApplet.java:10001)
	at noiseink.NoiseInk.main(NoiseInk.java:28)
Caused by: java.lang.ClassNotFoundException: com.sun.jna.Library
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more

**Comment by ThomasLengeling** [comment]
I haven't tried the lib using eclipse under ubnutu, it seems that its missing a the jna core packages, could be that jna is not link correctly or not installed
