### ISSUE TITLE
NoClassDefFoundError for Exported App (OS X)

### ISSUE THREAD

**Issue by brendanmatkin** [shiffman/OpenKinect-for-Processing#68]
Maybe similar to issue #51. 

OS x 10.11.4 
Processing 3.0.2
Kinect 1414

Sketch works fine in IDE but the exported app immediately crashes.  If I run in terminal I get: 
```
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: com/sun/jna/Library
...
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at org.openkinect.processing.Kinect.<init>(Unknown Source)
at (mySketch.setup())
...
Caused by: java.lang.ClassNotFoundException: com.sun.jna.Library
...
```
So, I THINK this is a problem with the openKinect library but that's about the limit of my knowledge. I'll keep digging but figured I'll post it here first! 

I can give more of the stack trace if it's helpful!

UPDATE: Same result whether or not java is embedded in the app (thought it might be a version thing maybe)

**Comment by shiffman** [comment]
Now being discussed in #70
